### ISSUE TITLE
git submodule update --init --recursive not work

### ISSUE THREAD

**Issue by yahi99** [openmaraude/APITaxi_devel#4]
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:openmaraude/APITaxi.git' into submodule path '/home/xxxx/workspace/APITaxi_devel/projects/APITaxi' failed
Failed to clone 'projects/APITaxi' a second time, aborting

**Comment by brmzkw** [comment]
Hey

What about `git clone git@github.com:openmaraude/APITaxi.git`?
It appears to be a permission issue on your side.

**Comment by DevatYHY** [comment]
Dear.. Sir,
I am from Africa, can i use this project for my country as non commercial.
thanks.

**Comment by brmzkw** [comment]
Yes, you can.
